Fix 'unused variable' error when HAVE_LIBFUSE && !HAVE_LIBSQLCIPHER
fuse_sqlfs.c: In function ‘main’:
fuse_sqlfs.c:27:14: error: unused variable ‘sqlfs’ [-Werror=unused-variable]
     sqlfs_t *sqlfs = 0;
              ^
cc1: all warnings being treated as errors

Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>