fix "unused variable" error
fuse_sqlfs.c: In function ‘main’:
fuse_sqlfs.c:27:14: error: unused variable ‘sqlfs’ [-Werror=unused-variable]
     sqlfs_t *sqlfs = 0;
              ^